---
- name: Install devspaces operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_name: devspaces
    install_operator_namespace: "{{ ocp4_workload_devspaces_namespace }}"
    install_operator_csv_nameprefix: devspacesoperator
    install_operator_channel: "{{ ocp4_workload_devspaces_channel }}"
    install_operator_starting_csv: "{{ ocp4_workload_devspaces_startingcsv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_devspaces_catalogsource_setup }}"
    install_operator_catalogsource_name: "{{ ocp4_workload_devspaces_catalogsource_name }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_devspaces_catalogsource_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_devspaces_catalogsource_tag }}"

- name: Create CheCluster
  kubernetes.core.k8s:
    state: present
    template: checluster.yaml.j2

- name: Wait until devspaces dashboard pod is ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
    - component=devspaces-dashboard
    namespace: "{{ ocp4_workload_devspaces_namespace }}"
  register: r_devspaces_dashboard_pod
  failed_when: r_devspaces_dashboard_pod.resources[0].status.phase | default('') != 'Running'
  until: r_devspaces_dashboard_pod is successful
  retries: 30
  delay: 10

- name: Create DevWorkspace(s)
  when: ocp4_workload_devspaces_setup_devworkspaces | bool
  block:
  - name: Check {{ ocp4_workload_devspaces_devworkspace_devfile }}
    kubernetes.core.k8s_exec:
      namespace: "{{ ocp4_workload_devspaces_namespace }}"
      pod: "{{ r_devspaces_dashboard_pod.resources[0].metadata.name }}"
      command: curl -sf "{{ ocp4_workload_devspaces_devworkspace_devfile }}"
    register: r_dashboard_check
    until:
    - r_dashboard_check.rc is defined
    - r_dashboard_check.rc == 0
    retries: 15
    delay: 5

  - name: Create DevWorkspace for single user
    when: ocp4_workload_devspaces_user_count is not defined
    vars:
      _ocp4_workload_devspaces_devworkspace_namespace: >-
        {{ ocp4_workload_devspaces_devworkspace_namespace_base }}{{ ocp4_workload_devspaces_username }}
      _ocp4_workload_devspaces_devworkspace_username: "{{ ocp4_workload_devspaces_username }}"
      _ocp4_workload_devspaces_devworkspace_git_repo: >-
        {{ ocp4_workload_devspaces_devworkspace_git_repo if ocp4_workload_devspaces_devworkspace_git_repo is defined
        else (ocp4_workload_devspaces_devworkspace_git_repo_base ~ '/'
        ~ ocp4_workload_devspaces_user_base ~ '/'
        ~ ocp4_workload_devspaces_devworkspace_git_repo_name
        if ocp4_workload_devspaces_devworkspace_git_repo_base is defined else "") }}
    ansible.builtin.include_tasks: create_dev_workspace.yml

  - name: Create DevWorkspace for multiple users
    when: ocp4_workload_devspaces_user_count is defined
    ansible.builtin.include_tasks: create_dev_workspace.yml
    vars:
      _ocp4_workload_devspaces_devworkspace_namespace: >-
        {{ ocp4_workload_devspaces_devworkspace_namespace_base }}{{ ocp4_workload_devspaces_user_base }}{{ n }}
      _ocp4_workload_devspaces_devworkspace_username: "{{ ocp4_workload_devspaces_user_base }}{{ n }}"
      _ocp4_workload_devspaces_devworkspace_git_repo: >-
        {{ ocp4_workload_devspaces_devworkspace_git_repo if ocp4_workload_devspaces_devworkspace_git_repo is defined
        else (ocp4_workload_devspaces_devworkspace_git_repo_base ~ '/'
        ~ ocp4_workload_devspaces_user_base ~ n ~ '/'
        ~ ocp4_workload_devspaces_devworkspace_git_repo_name
        if ocp4_workload_devspaces_devworkspace_git_repo_base is defined else "") }}
    loop: "{{ range(1, ocp4_workload_devspaces_user_count | int + 1) | list }}"
    loop_control:
      loop_var: n
      label: "{{ ocp4_workload_devspaces_user_base }}{{ n }}"

- name: Configure OAuth grant method
  when:
  - ocp4_workload_devspaces_oauth_grant_method is defined
  - ocp4_workload_devspaces_oauth_grant_method | length > 0
  kubernetes.core.k8s:
    api_version: oauth.openshift.io/v1
    kind: OAuthClient
    name: openshift-devspaces-client
    definition:
      grantMethod: "{{ ocp4_workload_devspaces_oauth_grant_method }}"
  register: r_oauth_grant_method
  retries: 30
  delay: 10
  until: r_oauth_grant_method is successful

- name: Save user information
  ansible.builtin.include_tasks: save_user_information.yml
